global:
    scrape_interval: 5s
    external_labels:
        monitor: 'faisal-monitor'
scrape_configs:
    - job_name: 'prometheus' 
      static_configs:
        - targets: ['172.31.41.45:9090'] ## IP Address of the localhost
    - job_name: 'node-exporter' 
      static_configs: 
        - targets: ['172.31.41.45:9100']
